# Generated by Django 3.1.1 on 2020-09-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200916_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='completed_distributions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='completed_send_orders',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='overall_rating',
            field=models.FloatField(null=True),
        ),
    ]
