# Generated by Django 3.1.1 on 2020-09-16 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200916_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='reviewed_by',
            new_name='reviewer',
        ),
        migrations.AddField(
            model_name='userreview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
