# Generated by Django 3.1.1 on 2020-09-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200916_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=1, null=True),
        ),
    ]
