# Generated by Django 3.1.1 on 2020-09-17 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_image', models.TextField(default='', null=True)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('delivery_contact_number', models.CharField(max_length=20)),
                ('goods_category', models.CharField(choices=[('Cash crop', 'Cash crop'), ('Vegetable', 'Vegetable'), ('Fruits', 'Fruits')], max_length=100)),
                ('description_of_goods', models.TextField(blank=True, max_length=500, null=True)),
                ('travel_schedule', models.DateTimeField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=100, null=True)),
                ('accepted_terms', models.BooleanField(default='', max_length=20, null=True)),
                ('booked_distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_distributor', models.BooleanField(default=False, max_length=20)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('purpose_of_travel', models.TextField(max_length=500, null=True)),
                ('active_contact_number', models.CharField(max_length=20)),
                ('mode_of_travel', models.CharField(choices=[('Commercial', 'Commercial'), ('Private', 'Private')], max_length=100)),
                ('additional_comment', models.TextField(blank=True, max_length=500, null=True)),
                ('travel_schedule', models.DateTimeField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
