# Generated by Django 3.1.1 on 2020-09-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_auto_20200917_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='delivered',
            field=models.BooleanField(default=False, max_length=20),
        ),
    ]
