# Generated by Django 3.1.1 on 2020-09-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_distributor_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='delivered',
        ),
        migrations.AddField(
            model_name='sender',
            name='delivered',
            field=models.BooleanField(default=False, max_length=20),
        ),
    ]
