# Generated by Django 3.1.1 on 2020-10-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_auto_20201001_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='active',
            field=models.BooleanField(default=False, max_length=20),
        ),
    ]
