# Generated by Django 3.1.1 on 2020-09-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
