# Generated by Django 3.1.1 on 2020-09-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0002_auto_20200915_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='transaction_no',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='ewallet.transactions'),
        ),
    ]
