# Generated by Django 3.1.1 on 2020-09-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0003_auto_20200917_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
