# Generated by Django 3.1.1 on 2020-09-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0004_auto_20200917_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_no',
            field=models.CharField(default='9962041398', max_length=50, unique=True),
        ),
    ]
