# Generated by Django 3.1.1 on 2020-09-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0005_auto_20200918_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_no',
            field=models.CharField(default='8902417277', max_length=50, unique=True),
        ),
    ]
