# Generated by Django 3.1.1 on 2020-09-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0006_auto_20200922_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_no',
            field=models.CharField(default='8289448661', max_length=50, unique=True),
        ),
    ]
